painting/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [

    path ('', views.blogs, name ='blogs'),
    path('<int:blog_id>/', views.detail, name ='detail' )

]

painting/painting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  #  standart for showing images:
from django.conf import settings
from sorting import views  #  for HTML pages:
from team import views as views_team


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name='about'),

    # магазин:
    path('shop/', views.shop, name = 'shop'),
    path('placing/', views.placing, name='placing'),
    # path('sold/', views.sold, name = 'sold'),
    path('picture/<int:picture_pk>/', views.picture, name='picture'),
    # проданные
    path('picture/<int:picture_pk>/sold', views.soldpicture, name='soldpicture'),
    path('picture/<int:picture_pk>/delete', views.deletepicture, name='deletepicture'),
    path('completedsold/', views.completedsold, name = 'completedsold'),

    # для регистрации:
    path('signup/', views_team.signupuser, name = 'signupuser'),
    path('logout',views_team.logoutuser, name = 'logoutuser'),
    path('login/', views_team.loginuser, name = 'loginuser'),



    # для задач:
    path('', views_team.home, name ='home'),
    path('current/', views_team.currentteam, name ='currentteam'),
    path('create/', views_team.createteam, name='createteam'),
    path('team/<int:team_pk>', views_team.viewteam, name ='viewteam'),
    path('team/<int:team_pk>/complete>', views_team.completeteam, name ='completeteam'),
    path('team/<int:team_pk>/delete>', views_team.deleteteam, name='deleteteam'),
    path('completed/', views_team.completedteam, name='completedteam'),

    # отзывы:
    path('feedback/', views.feedback, name='feedback'),
    path('feedbackall/', views.feedbackall, name='feedbackall'),

]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
                     document_root=settings.MEDIA_ROOT)

painting/sorting/models.py
from django.db import models
from django.contrib.auth.models import User



class Sorting(models.Model):
    name         = models.CharField(max_length=100)
    genre_author = models.CharField(max_length=500)
    picture      = models.ImageField(upload_to ='sorting/images/')
    links        = models.URLField(blank=True)  # -----links

    def __str__(self):
        return self.name




class Shop(models.Model):
    name         = models.CharField(max_length=100)
    picture      = models.ImageField(upload_to ='sorting/images/')
    author       = models.CharField(max_length=100)
    genre        = models.CharField(max_length=100)
    size         = models.CharField(max_length=30)
    price        = models.CharField(max_length=30)
    # links = models.URLField(blank=True)  # -----links

    def __str__(self):
        return self.name




class Feedbackall(models.Model):
    name         = models.CharField(max_length=100)
    text         = models.TextField(blank=True)
    created      = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

painting/sorting/forms.py
from django.forms import ModelForm
from .models import Shop, Feedbackall
from django import forms


class FeedbackallForm(ModelForm):
    class Meta:
        model = Feedbackall
        fields = ['name', 'text']



class ShopForm(ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'picture', 'author', 'genre', 'size', 'price']


        # widgets = {
        #     'genre': forms.EmailField(),
        # }
    #
    # def __init__(self, *args, **kwargs):
    #         super().__init__(*args, **kwargs)
    #
    #         for name, field in self.fields.items():
    #             field.widget.attrs.update({'class':'form_field'})

            # self.fields['name'].widget.attrs.update({'class':'form_field'})
            # self.fields['picture'].widget.attrs.update({'class':'form_field'})
            # self.fields['author'].widget.attrs.update({'class':'form_field'})
            # self.fields['genre'].widget.attrs.update({'class':'form_field'})
            # self.fields['size'].widget.attrs.update({'class':'form_field'})
            # self.fields['price'].widget.attrs.update({'class':'form_field'})

painting/sorting/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Sorting, Shop, Feedbackall
from .forms import ShopForm, FeedbackallForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# только для зарегистрированных пользователей.
from django.contrib.auth.decorators import login_required





# @login_required(login_url='index') # -------------!!!!
def about(request):
    return render(request, 'sorting/about.html')


# - Show page with pictures
def index(request):
    projects = Sorting.objects.all()
    return render(request, 'sorting/index.html', {'projects': projects})






                                       #  SHOP
def shop(request):
    pictures = Shop.objects.exclude(genre='sold')
    context = {'pictures': pictures}
    return render(request, 'sorting/shop.html', context)







def placing(request):
    form = ShopForm()
    if request.method == 'POST':
        form =ShopForm(request.POST, request.FILES)
        if  form.is_valid():
            form.save()
            return redirect('shop')
    context = {'form': form}
    return render(request, 'sorting/placing.html', context)



# ----------------- CURRENT --------------

def picture(request, picture_pk):
    picture = get_object_or_404(Shop, pk=picture_pk)
    if request.method == "GET":

        form  = ShopForm(instance = picture)
        return render(request, 'sorting/picture.html', {'picture': picture, 'form':form})

    else:
        try:
            form = ShopForm(request.POST, instance = picture)
            form.save()
            return redirect('shop')
        except ValueError:
            return render(request, 'sorting/shop.html',
                          {'picture': picture, 'form': form, 'error': 'Неверные данные'})





def soldpicture(request, picture_pk):
    picture = get_object_or_404(Shop, pk=picture_pk)
    if request.method == 'POST':
        picture.genre='sold'
        picture.save()
        return redirect('completedsold')





@login_required(login_url='loginuser')
def deletepicture (request, picture_pk):
    picture = get_object_or_404(Shop, pk=picture_pk )
    if request.method == 'POST':
        picture.delete()
        return redirect('shop')


def completedsold(request):
    teams = Shop.objects.filter(genre='sold')
    return render(request, 'sorting/completedsold.html', {'teams': teams})









# @login_required
# def deleteteam(request, team_pk):
#     team = get_object_or_404(Team, pk=team_pk, user=request.user)
#     if request.method == 'POST':
#         team.delete()
#         return redirect('shop')






                        #           F E E D B A C K


@login_required(login_url='loginuser') # redirection
def feedback(request):
    form = FeedbackallForm()
    # return render(request, 'sorting/feedback.html')

    if request.method == 'POST':
        form =FeedbackallForm(request.POST, request.FILES)
        if  form.is_valid():
            form.save()
            return redirect('feedbackall')
    context = {'form': form}
    return render(request, 'sorting/feedback.html', context)




def feedbackall(request):
    feedbacks = Feedbackall.objects.all()
    context = {'feedbacks': feedbacks}
    return render(request, 'sorting/feedbackall.html', context)

painting/sorting/templates/sorting/about.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}

<div>
    <p class ='about'> Information about Python which is the language of this site: </p>
          <div class="'picture">
                <a href =' https://www.python.org/'>
                    <img class = 'pic' src='{% static "sorting/pic.jpg" %}' alt ="">
                </a>
          </div>
</div>


{% endblock %}

painting/sorting/templates/sorting/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="description" content="Сайт о живописи." />
     <title>Title</title>
     <link rel="stylesheet" href="{% static 'css/ustyleone.css' %}">
     <link rel="icon"  type="image/x-icon"  href="{% static 'sorting/favicon.ico' %}">

</head>
    <body>

<div class = 'menu'>
    <div class = 'wrap'>
            <div class="">
                <a href =' {%  url "index" %}'>
                    <img src='{% static "sorting/logo_history.jpg" %}' alt ="">
                </a>
            </div>

            <ul>
                <li><a href=" {%  url 'index' %} ">Главная</a></li>
                <li><a href=" {%  url 'shop' %}  "> Галерея </a></li>
                <li><a href="{% url 'completedsold' %}"> Проданные </a></li>
                <li><a href=" {%  url 'blog:blogs' %}  ">Блог</a></li>
                <li><a href=" {%  url 'loginuser' %} ">Авторизация</a></li>

             </ul>
    </div>
</div>



                      <div class ='wrap'>
                        {% block content %}

                        {% endblock %}
                      </div>


<div class = 'footer'>
    <div class = 'wrap1 footer_content'>
        <ul>
            <li><a  class = 'footer_a' href=" {% static 'sorting/History_art.pdf' %} "  target='_blank'>Статья</a></li>
            <li><a  class = 'footer_a' href=" {%  url 'about' %}" target="_blank">О сайте</a></li>
            <li><a  class = 'footer_a' href=" {%  url 'feedback' %}" target="_blank">Отправить отзыв (для авторизованных пользователей)</a></li>
            <li><a  class = 'footer_a' href=" {%  url 'feedbackall' %}" target="_blank">Отзывы</a></li>
        </ul>



    </div>


    <div class = 'wrap1 footer_content'>

         <ul>
              <li>  <span> Контакты:  </span></li>
              <li>  <span> Телефон: 123-45-67  </span></li>
              <li>  <span> Почта: painting@mail.com  </span></li>
         </ul>

    </div>


</div>



    </body>

</html>

painting/sorting/templates/sorting/completedsold.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}



<h1> Купленные картины </h1>

<div class="wrap_completedsold">
    {% for team in teams  %}
<div class="block_completedsold">
         <ul>
             <li>{{ team.name }} </li>
             <li> Состояние: {{ team.genre }} </li>
             <li>  {{ team.price }} </li>
         </ul>


         <div class ='element'>
            <div>
                <img class='pic3'  src="{{ team.picture.url }}" alt=''>
            </div>
         </div>


</div>


    {% endfor %}
</div>


{% endblock %}

painting/sorting/templates/sorting/feedback.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}


<h3> Оставьте отзыв </h3>

<form class='bg' method="POST"  enctype="multipart/form-data">
         {% csrf_token %}

          <div class="form__field">
               <label for="formInput#text"> Имя {{  form.name }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text">Текст {{  form.text }} </label>
            {{ field }}
          </div>
    <input class="btn" type="submit" value='Разместить'/>



</form>




{% endblock %}

painting/sorting/templates/sorting/feedbackall.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}


<h2> Отзывы </h2>


<div class = 'block'>
    {% for feedback in feedbacks %}
    <div class = 'block1'>
                 <div class = 'text1'>

                        <p class ='text_about'>Автор: {{ feedback.name }}</p>
                        <p class ='text_about'> Текст отзыва: {{ feedback.text }}</p>
                        <p class ='text_about'> Дата: {{ feedback.created }}</p>

                 </div>
    </div>
    {% endfor %}
</div>



{% endblock %}

painting/sorting/templates/sorting/index.html
{%  extends 'sorting/base.html'  %}
{% load static %}
{% block content %}


             <h1>  Живопись  </h1>
<!--             <p class="test">TEST</p>-->


<div class='img' >
    <img class='pic2' src="{% static 'sorting/Palitra.jpg' %}" alt ='' >
</div>


    <p class='description'>
        Живопись – это вид искусства, позволяющий запечатлеть красоту
        окружающего мира на холсте или другой поверхности с помощью красок.
        Она обладает выразительными средствами, которые передают эмоциональную
        окраску картин.
    </p>


<div class = 'block'>

    {% for project in projects %}
<div class = 'block_main'>

        <div class = 'text'>
            <h2><a href="{{ project.links }}" target ='_blank' >{{ project.name }} </a></h2>
        </div>

        <div class ='element' >
                <img class='pic3' id="elem" src="{{ project.picture.url }}" alt=''>
        </div>

        <div class = 'text'>
            <p class ='genre'>{{ project.genre_author|safe }}</p>
        </div>
</div>
    {% endfor %}
</div>


{% endblock %}

painting/sorting/templates/sorting/picture.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}

{{ error }}

<!--{{  picture.name  }}-->

<!--{{ picture.picture }}-->


{% if user.is_authenticated %}
<form method ="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class ='btn'> Сохранить </button>
</form>
{% endif %}



{% if user.is_authenticated %}
    <form action ='{% url "soldpicture" picture.id  %}' method ='POST' enctype="multipart/form-data">
        {%  csrf_token %}
        <button class = "btn "> Купить </button>
    </form>

{% else %}
    <form action ='{% url "soldpicture" picture.id  %}' method ='POST' enctype="multipart/form-data">
        {%  csrf_token %}
            <div class = 'wrap'>
        <ul>
            <li>  {{ picture.name }}   </li>
            <li>  {{ picture.author }} </li>
            <li>  {{ picture.price }}  </li>
        </ul>
            </div>
        <button class = "btn "> Купить </button>
    </form>
{% endif %}





{% if user.is_authenticated %}
    <form action ='{% url "deletepicture" picture.id  %}' method ='POST' enctype="multipart/form-data">
        {%  csrf_token %}
        <button class = "btn "> Удалить </button>
    </form>
{% endif %}









{% endblock %}

painting/sorting/templates/sorting/placing.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}



<h2>Разместите картину в магазине </h2>


<h2>  {{ error }}  </h2>

<form class='bg' method="POST"  enctype="multipart/form-data">
         {% csrf_token %}

          <div class="form__field">
               <label for="formInput#text"> Название {{  form.name }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text">Изображение {{  form.picture }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text"> Автор {{  form.author }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text"> Жанр {{  form.genre }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text"> Размер {{  form.size }} </label>
            {{ field }}
          </div>

          <div class="form__field">
               <label for="formInput#text"> Цена {{  form.price }} </label>
            {{ field }}
          </div>


    <input class="btn" type="submit" value='Разместить'/>
</form>








{% endblock %}

painting/sorting/templates/sorting/shop.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}

<h1> Галерея </h1>
<p class='description'> Тут вы можете приобрести работы художников.</p>



{% if user.is_authenticated %}

                        <ul>
                            <li class = 'shop_description  q'>
                                <a href=" {%  url 'placing' %} ">  Разместить работу  </a>
                            </li>
                        </ul>


{% else %}

                    <ul>
                        <li class = 'shop_description'>
                            Для размещения работ в магазине нужно
                            <a href="{% url 'loginuser' %}">
                                Войти.
                            </a>
                        </li>
                    </ul>

{% endif %}



<div class = 'wrap_shop'>



{% for picture in pictures %}
<div class = 'block_shop'>
         <div class = 'text'>
                <h2><a href="{{ project.links }}" target ='_blank' >{{ picture.name }}</a></h2>
         </div>

         <div class ='element'>

                    <img class='pic4' id='elem' src="{{ picture.picture.url }}" alt=''>

         </div>

         <div class = 'text'>
                <p class ='genre'>Автор: {{ picture.author }}</p>
                <p class ='genre'>Жанр: {{ picture.genre }}</p>
                <p class ='genre'>Размер: {{ picture.size }}</p>
                <p class ='genre'>Цена: {{ picture.price }}</p>
         </div>


        <div>
              <a href ='{% url "picture" picture.id %}'>  <button>  Купить  </button></a>
              {% if user.is_authenticated %}
              <a href ='{% url "picture" picture.id %}'> <button> Редактировать </button></a>
              {% endif %}
        </div>
</div>
{% endfor %}


</div>



{% endblock %}

painting/sorting/templates/sorting/sold.html
{% extends 'sorting/base.html' %}

{% load static %}

{% block content %}




<p> SOLD </p>

    {% for team in teams  %}


     {{ team.name }}
     {{ team.price }}


        {% endfor %}


{% endblock %}